# Dependencies
markdown: kramdown
highlighter: rouge

repository: jasontthai/jasonthai.me-source
email: '&#104;&#101;&#121;&#064;&#106;&#097;&#115;&#111;&#110;&#116;&#104;&#097;&#105;&#046;&#109;&#101;'
title: Jason's Notes
description: Jason Thai's personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasonthai.me" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Jason Thai
  avatar: /assets/img/profile.jpeg
  description: Jason's personal page

# paginate:         5
# paginate_path:    '/page/:num'
pagination:
  enabled: false
  debug: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

header_pages:
  - about.md
  - posts.md
  - services.html
  - visited-places.html

# disqus:
#  shortname: https-jasonthai-me

github_username: jasontthai
linkedin_username: jasontthai
rss: Feed

show_excerpts: true
excerpt_separator: <!--more-->

permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-admin
  - jekyll-coffeescript
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-toc
  - jekyll-last-modified-at
  - jekyll-loading-lazy
  - jekyll-archives

exclude:
  - .travis.yml
  - bin/*
  - .circle/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
  - vendor
  - node_modules/*
  - tailwind.config.js
