# Dependencies
markdown: kramdown
highlighter: rouge

# remote_theme: fongandrew/hydeout
theme: minima
email: '&#104;&#101;&#121;&#064;&#106;&#097;&#115;&#111;&#110;&#116;&#104;&#097;&#105;&#046;&#109;&#101;'
title: Jason's Notes
description: Jason Thai's personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasonthai.me" # the base hostname & protocol for your site, e.g. http://example.com
# author: Jason Thai
author:
  name: Jason Thai
  avatar: /assets/img/profile.webp
  description: Jason's personal page

# paginate:         5
# paginate_path:    '/page/:num'
pagination:
  enabled: true
  debug: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

header_pages:
  - about.md
  - posts.md
  - categories.html
  - visited-places.html

# disqus:
#  shortname: https-jasonthai-me

github_username: zirius
linkedin_username: jasontthai
rss: Feed

show_excerpts: true
excerpt_separator: <!--more-->

ads_enable: false

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      tag: "en"
  -
    scope:
      path: "_posts/vi"
      type: "posts"
    values:
      tag: "vi"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-admin
  - jekyll-coffeescript
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-toc

# sidebar_home_link: true

google_analytics: UA-120912817-1

exclude:
  - .travis.yml
  - bin/*
  - .circle/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
  - vendor
  - node_modules/*
