- name: Gitea
  description: Gitea is a community managed lightweight code hosting solution written in Go. It is published under the MIT license.
  url: https://git.jasonthai.me
  icon: /assets/img/services/gitea.png

- name: TT-RSS
  description: Free and open source web-based news feed (RSS/Atom) reader and aggregator. Contact me for an account.
  url: https://rss.jasonthai.me
  icon: /assets/img/services/rss.png

- name: Nextcloud
  description: The self-hosted productivity platform that keeps you in control. Data is encrypted. Contact me for a free 4GB space.
  url: https://cloud.jasonthai.me
  icon: /assets/img/services/cloud.png

- name: Wallabag
  description: Wallabag is an open source project to save your web articles and allows you to read them later on your mobile devices.
  url: https://wallabag.jasonthai.me
  icon: /assets/img/services/wallabag.png

- name: Bitwarden
  description: The easiest and safest way for individuals, teams, and business organizations to store, share, and sync sensitive data.
  url: https://bitwarden.jasonthai.me
  icon: /assets/img/services/passwordmanager.png

- name: xBrowserSync
  description: Sync your bookmarks between browsers and devices while maintaining your privacy and anonymity.
  url: https://xbrowsersync.jasonthai.me
  icon: /assets/img/services/browsersync.png


