version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:latest-node
        environment:
          USER_NAME: zirius
          USER_EMAIL: thaixtri@gmail.com
    steps:
      - checkout
      - run: sudo apt install rsync -y
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
      - restore_cache:
          keys:
            - v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v2-gem-cache-{{ arch }}-{{ .Branch }}-
            - v2-gem-cache-{{ arch }}-
      - run: bundle install --path=vendor/bundle && bundle clean
      - save_cache:
          paths:
            - vendor/bundle
          key: v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: JEKYLL_ENV=production bundle exec jekyll build
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install workbox-cli
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npx workbox injectManifest workbox-config.js
      # - run:
      #     name: Test
      #     command: bundle exec htmlproofer ./_site --check-html --disable-external --empty-alt-ignore
      - add_ssh_keys:
          fingerprints:
            - "8e:14:d6:3a:d2:e4:e1:8a:41:19:91:00:b2:f2:ec:74"
      - run: ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
